# Intent definition for Calendar skill
#
#  (c) A. Dominik, 2020
#
skill = "ADoSnipsIrrigation"
developer = "andreasdominik"


# the skill uses the QnD-On/Off-intent, with the slot "device"
[inventory]
intents = ["IrrigationOn", "IrrigationOff"]
slots = []


# intents:
#
[IrrigationOn]
irrigation_a = "partial: starte <<bitte|>> die <<Gartenbewässerung|Bewässerung>>"
irrigation_b = "exact: <<bitte|>> bewässere <<bitte|>> den Garten"
irrigation_c = "exact: <<bitte|>> gieße <<bitte|>> den Garten"

[IrrigationOff]
irrigation_off = "exact: <<bitte|>> höre auf den Garten zu bewässern"
irrigation_off_b = "exact: <<bitte|>> <<stoppe|beende>> <<bitte|>> die Bewässerung"
